### ISSUE TITLE
Parameter order & please git the results

### ISSUE THREAD

**Issue by HJLebbink** [WojciechMula/ternary-logic#1]
Thanks for the useful library. 

The parameters are reversed compared to the parameter order in the compiler intrinsics. This is **very** confusing. 

```
ternary_logic::sse::ternary<0x30>(c, b, a) = a&!b
_mm512_ternarylogic_epi64(a, b, c, 0x30) = a&!b
```

**Request:** could you please provide (git) the resulting files. I had to install python just to get these files, they could just as well been added to the repository.

**Comment by WojciechMula** [comment]
@HJLebbink I'm glad to hear you find the library useful. I believe I have done all you asked for, please verify.

**Comment by HJLebbink** [comment]
Yes, thanks, the reversed parameter order made debugging somewhat tormenting...
